---
user-service:
  port: 50051
post-service:
  port: 50052
like-service:
  port: 50053
outbox-service:
  port: 50054
database:
  username: yaninyzwitty
  host: vague-echidna-13927.j77.aws-eu-central-1.cockroachlabs.cloud
  database: defaultdb
  port: 26257
queue:
  url: pulsar+ssl://pulsar-gcp-europewest1.streaming.datastax.com:6651
  topic_name: persistent://witty-tenant/default/likes